config/routes.rb
Todobadour::Application.routes.draw do
  # Lists resource
  resources :lists, :only => [:create, :show, :destroy, :update, :email] do
    member do
      post :email
    end
    resources :todos, :only => [:create, :destroy, :update]
  end
    
  # Static Pages
  root to: "high_voltage/pages#show", id: "home"

end

app/models/faye_message.rb
require "net/http"

class FayeMessage

  attr_reader :config

  def initialize
    config_path = File.join(File.dirname(__FILE__), "..", "..", "config", "faye.yml")
    @config = YAML.load_file(config_path)[Rails.env].symbolize_keys!
  end

  def publish(event, channel, message)
    message = { channel: "/#{channel}/#{event}", data: message, ext: { auth_token: config[:token] } }
    Net::HTTP.post_form(faye_uri, message: message.to_json)    
  end

  def faye_js_url
    "#{faye_host}/faye.js"
  end

  def faye_server
    "#{faye_host}/faye"
  end

  private 
  def faye_uri
    URI.parse("#{faye_server}")
  end

  def faye_host
    "http://#{config[:host]}:#{config[:port]}"
  end


end

app/models/list.rb
class List < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug

  attr_accessible :title, :description, :slug

  has_many :todos, :dependent => :destroy

  before_validation :generate_and_add_slug

  validates :title, :presence => true,
                    :length => { :maximum => 140 }

  validates :slug, :uniqueness => true,
                   :presence => true

  class << self
    def for_slug(slug)
      where(slug: slug).limit(1).first
    end
  end

  def ordered_todos
    self.todos.rank(:position)
  end

  def share_via_email sender, receiver, message
    ShareMailer.share_list(self, sender, receiver, message).deliver
  end

  private
    # generate a slug if none present before trying to validate
    def generate_and_add_slug
      if self.slug.nil? || self.slug.empty?
        self.slug = SecureRandom.hex 16
      end
      self
    end
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :list

  before_validation :default_values

  validates :title, :presence => true,
                    :length => { :maximum => 140 }

  validates :list_id, :presence => true

  include RankedModel
  ranks :position

  private
    def default_values
      self.done ||= false
      self
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  respond_to :html, :json, :js

  def show
    @list = List.for_slug(params[:id])
    @todo = Todo.new
    # Save list to cookie
    cookies[:last_list] = { :value => @list.slug, :expires => 14.day.from_now }
  end

  def create
    @list = List.new params[:list]
    respond_to do |format|
      if @list.save
        format.js { render js: "window.location.href = ('#{list_path(@list)}');" }
        format.html { redirect_to @list }
      else
        format.js { render partial: "shared/error_messages", locals: { object: @list } }
        format.html { redirect_to root_path }
      end
    end
  end

  def destroy
    List.for_slug(params[:id]).destroy
    # Remove the cookie if the list is destoried!
    cookies.delete :last_list
    redirect_to root_path
  end

  def update
    @list = List.for_slug(params[:id])
    list = params[:list]

    # Save ranking
    if list[:todos]
      @list.todos.each do |todo|
        todo.position = list[:todos].index("todo_#{todo.id}")
        todo.save
      end
      list.delete(:todos)
    end

    # save other updates
    respond_to do |format|
      if @list.update_attributes list
        format.html { redirect_to @list }
        format.json { respond_with_bip @list }
      else
        format.html { redirect_to @list, notice: "update list failed" }
        format.json { render json: @list.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  def email
    @list = List.for_slug(params[:id])

    receiver = params[:receiver]
    sender = params[:sender]
    message = params[:message]

    @list.share_via_email sender, receiver, message

    respond_with(@list) do |format|
      format.js
      format.json { true.to_json }
      format.html { render @list }
    end

  end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  respond_to :html, :js, :json

  def create
    @list = current_list
    @todo = @list.todos.build params[:todo]
    @todo.position = RankedModel::MIN_RANK_VALUE
    respond_to do |format|
      if @todo.save
        format.js
        format.html { redirect_to current_list }
      else
        format.js { render :partial => "shared/error_messages", :locals => { :object => @todo } }
        format.html { redirect_to current_list }
      end
    end
  end

  def destroy
    @removeId = params[:id]
    Todo.find(@removeId).destroy
    @list = current_list
    respond_with() do |format|
      format.js
      format.html { redirect_to current_list }
    end
  end

  def update
    @todo = Todo.find params[:id]
    respond_to do |format|
      if @todo.update_attributes params[:todo]
        FayeMessage.new.publish("update", current_list.slug, @todo.to_json)
        format.html { redirect_to current_list }
        format.json { respond_with_bip @todo }
      else
        format.html { redirect_to current_list }
        format.json { render :json => @todo.errors.full_messages, :status => :unprocessable_entity }
      end
    end
  end

  private

    def current_list
      List.for_slug params[:list_id]
    end

    def todo_list todo
      List.find todo.list_id
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  # Load Facebook Share
  include FacebookShare
  
  # Make the title configurable and available everywhere
  def page_title
    title = content_for?(:title) ? " - #{content_for(:title)}" : ""
    "Todobadour#{title}"
  end

  def page_heading(text)
    content_tag(:h1, content_for(:title){ text })
  end

  # check if we passed a list if not create a new one
  def list
    @list.nil? ? List.new : @list
  end

  # publish a message given as a block
  def publish(channel, event, &block)
    FayeMessage.new.publish(event, channel, capture(&block))
  end

  # js url to include the faye js
  def faye_js
    FayeMessage.new.faye_js_url
  end

  def faye_server
    FayeMessage.new.faye_server
  end

    
end

app/helpers/lists_helper.rb
module ListsHelper
  
  def last_list
    if cookies["last_list"]
      begin 
        list = List.for_slug cookies["last_list"].dup.force_encoding(Encoding::UTF_8)      
      rescue ActiveRecord::RecordNotFound => e
        list = nil
      end
    else 
      list = nil
    end
    list
  end
        
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <%= link_to "Todobadour", root_path %>
  <%= link_to "About", page_path("about")%>
</div>

app/views/layouts/_header.html.erb
<div class="header">
  <%= render "lists/last_visited_list" %>
</div>

app/views/layouts/_iefixes.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<!–[if IE]>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= page_title %></title>
  <%= render "layouts/iefixes" %>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application", "#{faye_js}" %>
  <%= javascript_tag "var FAYE_URL = '#{faye_server}';" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">

<%= render "layouts/header" %>

<div class="content">
<%= yield %>
</div>

<%= render "layouts/footer" %>

<% if false && Rails.env.development? %>
  <div style="clear:both;">
  <%= debug(params) %>
<% end %>

<% if Rails.env.production? %>
  <%= analytics_init %>
  <%= facebook_share_once %>
<% end %>

</div>
</body>
</html>

app/views/lists/_email_form.html.erb
<div id="email-share-form">
<%= form_for @list, :url => email_list_path, :method => :post, :remote => true do |f| %>
  <%= render "shared/error_messages", :object => f.object %>
  <div>
    <%= label_tag 'You' %>
    <%= email_field_tag :sender %>
  </div>
  <div>
    <%= label_tag 'Share with' %>
    <%= email_field_tag :receiver %>
  </div>
  <div>
    <%= text_area_tag :message, "I need some help", rows: 1, class: "common" %>
  </div>
  <div>
    <%= f.submit 'Send EMail', class: ["send_email", "button"] %>
  </div>
<% end %>
</div>

app/views/lists/_last_visited_list.html.erb
<% unless last_list.nil? %>
  <%= link_to "Check your last list #{last_list.title}", last_list %>
<% end %>

app/views/lists/_list_short_form.html.erb
<div class="list-create-short">
<%= form_for list, remote: true do |f| %>
  <div>
    <%= f.text_field :title, placeholder: "Enter list name" %>
  </div>
  <div>
    <%= f.submit "Make a list", class: "button" %>
  </div>
<% end %>
</div>

app/views/lists/_share.html.erb
<div class="share">

  <%= link_to image_tag("mail.png", size: "32x32", alt: "share via email"), "#", id: "email-share" %>

  <%= link_to image_tag("twitter.png", size: "32x32", alt: "share on twitter"), "http://twitter.com/home?status=Help me with #{@list.title} #{list_url(@list)} (via Todobadour)"%>

  <%= link_to image_tag("facebook.png", size: "32x32", alt: "share on facebook"), '#', :class => "fb_share"  %>

  <%= render "email_form" %>

</div>

app/views/lists/_todolist.html.erb
<ul id="todo-list">
  <%= render todos %>
</ul>

app/views/lists/email.js.erb
(function($){
  $(function(){
    $("#sender").val("");
    $("#receiver").val("");
    $("#message").val("");
    $("#email-share-form").slideUp("fast");
    $("<div>Email sent</div>").purr({
      fadeInSpeed: 200,
      fadeOutSpeed: 2000,
    removeTimer: 5000 });
  });
})(jQuery);

app/views/lists/show.html.erb
<%= javascript_tag "var LIST_ID = '#{@list.slug}';" %>

<div class="list-header">
  <div class="edit-icon">
    <%= image_tag("wrench_24x24.png") %>
  </div>
  <h1><%= best_in_place @list, :title %></h1>
  <div class="trash-link">
    <%= link_to image_tag("trash_stroke_24x24.png", alt: "delete"),
      @list, method: :delete, data: { confirm: "Are you sure?" }, title: @list.title %>
  </div>
</div>

<%= render "share"%>

<%= render "todos/todo_form" %>

<% if @list.todos.empty? %>
  <ul id="todo-list"></ul>
<% else %>
  <%= render :partial => "todolist", :locals => { :todos => @list.ordered_todos }%>
<% end %>

app/views/lists/update.js.erb
<% publish @list.slug, "list_update" do %>
	<%= render( :partial => "lists/todolist", :locals => { :todos => @list.ordered_todos }) %>
<% end %>

app/views/pages/about.html.erb
<%= page_heading "About" %>
<h1>About</h1>

<p>
  Todobadour sets out to be managing todos as easy as doodle does for meetings, hope you enjoy!
</p>

<p>
  Any feedback is greatly appriciated just email to <a
  href="mailto:phil@cospired.com">phil@cospired.com</a> or visit <a
  href="http://sideshowcoder.com">my blog</a>
</p>

app/views/pages/home.html.erb
<h1>Todobadour lists</h1>
<h3>Easy to create and easy to share</h3>

<%= render "lists/list_short_form" %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluarlize(object.errors.count, "error") %> prevented saving</h2> 
    <p>There where problems with the following fields:</p>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages.js.erb
<% if object.errors.any? %>
  <% object.errors.full_messages.each do |msg| %>
    (function($){
      $(function(){
        $( "<div>" + "<%= msg %>" + "</div>")
        .purr({ fadeInSpeed: 200, fadeOutSpeed: 2000, removeTimer: 5000 });
      });
    })(jQuery);
  <% end %>
<% end %>

app/views/todos/_todo.html.erb
<li id='todo-<%= todo.id %>' class='<%= todo.done? ? "done" : "not-done" %>'>
  <span class="edit-icon">
    <%= image_tag("wrench_16x16.png") %>
  </span>
  <span class='title'>
    <%= best_in_place todo, :title, :path => list_todo_path(@list, todo) %>
  </span>
  <span class="manage">
    <span class='done'>
      <%= best_in_place todo, :done, :type => :checkbox,
                                     :collection => ["✓", "☓"],
                                     :path => list_todo_path(@list, todo) %>
    </span>
    <span class="trash-link">
      <%= link_to image_tag("trash_stroke_16x16.png", alt: "delete"),
        [@list, todo], method: :delete, remote: true, title: todo.title %>
    </span>
  </span>

</li>

app/views/todos/_todo_form.html.erb
<div id="todo-form">
<%= form_for [@list, @todo], :remote => true do |f| %>
  <%= render "shared/error_messages", :object => f.object %>
  <div>
    <%= f.text_field :title, placeholder: "New todo", class: "submittable" %>
  </div>
  <div>
    <%= f.submit "Add", type: :image, src: "/assets/plus_alt_24x24.png", class: "add" %>
  </div>
<% end %>
</div>

app/views/todos/create.js.erb
<% publish @list.slug, "add" do %>
	<%= render @todo %>
<% end %>

(function($){
  $(function(){ $('#todo_title').val(''); });
})(jQuery);

app/views/todos/destroy.js.erb
<% publish @list.slug, "remove" do %>
	<%= "#todo-#{@removeId}" %>
<% end %>